# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
   CLUSTER_NAME: controlplane

includes: 
  argocd:
    taskfile: ./argocd/Taskfile.yml
    dir: ./argocd
  
  traefik:
    taskfile: ./traefik/Taskfile.yml
    dir: ./traefik

tasks:
 
  cluster:create:
    label: Talos create cluster
    desc: Create a new talos cluster for the controlplane
    cmds:
      - talosctl cluster create --name {{ .CLUSTER_NAME }} --context {{ .CLUSTER_NAME }} --exposed-ports 8443:30443/tcp,9443:9443/tcp
  

  cluster:destroy:
    label: Talos delete cluster
    desc: Delete talos cluster for the controlplane
    cmds:
      - talosctl cluster destroy --name {{ .CLUSTER_NAME }} --context {{ .CLUSTER_NAME }}
      - talosctl config remove {{ .CLUSTER_NAME }}


  cluster:show:
    cmds:
      - pwd
      - talosctl cluster show --name {{ .CLUSTER_NAME }} --context {{ .CLUSTER_NAME }}
    desc: Show controlplane cluster
  

 

