# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: '3'
tasks:
  install:
   
    cmds:
      - pwd
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm upgrade --install my-argo-cd argo/argo-cd -f values.yml --create-namespace --namespace argocd
  admin_pw:
    cmds: 
      - "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath=\"{.data.password}\" | echo ArgoCD Password: $(base64 -d) \n"
